# Generated by Django 4.2.23 on 2025-10-06 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretaryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('LOW', 'low'), ('MEDIUM', 'medium'), ('HIGH', 'high'), ('URGENT', 'urgent')], default='MEDIUM', max_length=12)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('IN_PROGRESS', 'in-progress'), ('COMPLETED', 'completed'), ('OVERDUE', 'overdue')], default='PENDING', max_length=15)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(choices=[('MEMBERSHIP', 'membership'), ('FINANCE', 'finance'), ('EVENTS', 'events'), ('COMMUNICATION', 'communication'), ('ADMINISTRATION', 'administration')], default='ADMINISTRATION', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('CARD_ISSUE', 'card-issue'), ('PROFILE_UPDATE', 'profile-update'), ('GROUP_JOIN', 'group-join'), ('PRAYER_REQUEST', 'prayer-request'), ('OTHER', 'other')], max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'new'), ('PROCESSING', 'processing'), ('COMPLETED', 'completed')], default='NEW', max_length=12)),
                ('urgency', models.CharField(choices=[('NORMAL', 'normal'), ('URGENT', 'urgent')], default='NORMAL', max_length=10)),
                ('details', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretary_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('SUCCESS', 'success'), ('WARNING', 'warning'), ('INFO', 'info')], default='INFO', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
