# Generated by Django 4.2.23 on 2025-10-06 13:49

import ChurchSecreatary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserAuthentication', '0003_member_role'),
        ('ChurchSecreatary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('code', models.CharField(db_index=True, max_length=16, unique=True)),
                ('is_taken', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_offering_cards', to=settings.AUTH_USER_MODEL)),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offering_cards', to='UserAuthentication.street')),
            ],
            options={
                'ordering': ['street__name', 'number'],
                'unique_together': {('street', 'number')},
            },
        ),
        migrations.CreateModel(
            name='OfferingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('AHADI', 'Ahadi'), ('SHUKRANI', 'Shukrani'), ('MAJENGO', 'Majengo')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='ChurchSecreatary.offeringcard')),
            ],
        ),
        migrations.CreateModel(
            name='CardAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField(default=ChurchSecreatary.models.current_year)),
                ('pledged_ahadi', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pledged_shukrani', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pledged_majengo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='ChurchSecreatary.offeringcard')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offering_card_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
