# Generated by Django 4.2.23 on 2025-10-13 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChurchSecreatary', '0003_registrationwindow_cardapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardassignment',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='ChurchSecreatary.offeringcard'),
        ),
        migrations.AlterUniqueTogether(
            name='cardassignment',
            unique_together={('card', 'year')},
        ),
    ]
