# Generated by Django 4.2.23 on 2025-10-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChurchSecreatary', '0004_alter_cardassignment_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardapplication',
            name='pledged_ahadi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cardapplication',
            name='pledged_majengo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cardapplication',
            name='pledged_shukrani',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
