# Generated by Django 4.2.23 on 2025-10-13 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChurchSecreatary', '0005_cardapplication_pledged_ahadi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardapplication',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='ChurchSecreatary.cardassignment'),
        ),
    ]
