# Generated by Django 4.2.23 on 2025-10-15 12:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthentication', '0003_member_role'),
        ('ChurchSecreatary', '0006_cardapplication_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorder_name', models.CharField(max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('mass_type', models.CharField(choices=[('MAJOR', 'Major'), ('MORNING_GLORY', 'Morning Glory'), ('EVENING_GLORY', 'Evening Glory'), ('SELI', 'SELI')], max_length=50)),
                ('major_mass_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offering_batches', to='UserAuthentication.street')),
            ],
        ),
        migrations.AddField(
            model_name='offeringentry',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='ChurchSecreatary.offeringbatch'),
        ),
    ]
