# Generated by Django 4.2.23 on 2025-09-18 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserAuthentication', '0003_member_role'),
        ('churchMember', '0002_dailydevotional_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='event_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('EVENTS', 'Events'), ('SERVICE_CHANGES', 'Service Changes'), ('COMMUNITY_NEWS', 'Community News'), ('URGENT_UPDATES', 'Urgent Updates'), ('GENERAL', 'General')], default='GENERAL', max_length=100),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='target_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserAuthentication.group'),
        ),
    ]
