# Generated by Django 4.2.23 on 2025-09-21 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('churchMember', '0003_announcement_event_date_announcement_event_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='announcement',
            name='rsvp_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('events', 'Events'), ('services', 'Service Changes'), ('community', 'Community News'), ('urgent', 'Urgent Updates'), ('general', 'General')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_by',
            field=models.CharField(default='Church Office', max_length=100),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='target_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
