# Generated by Django 4.2.23 on 2025-10-02 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('churchMember', '0005_announcement_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevotionalInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmarked', models.BooleanField(default=False)),
                ('amened', models.BooleanField(default=False)),
                ('journal', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('devotional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='churchMember.dailydevotional')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('member', 'devotional')},
            },
        ),
    ]
