# Generated by Django 4.2.23 on 2025-10-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchMember', '0007_prayerreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering',
            name='offering_type',
            field=models.CharField(choices=[('TITHE', 'Tithe'), ('SPECIAL_OFFERING', 'Special Offering'), ('GENERAL_CONTRIBUTION', 'General Contribution'), ('AHADI', 'Ahadi'), ('SHUKRANI', 'Shukrani'), ('MAJENGO', 'Majengo')], max_length=50),
        ),
    ]
