# Generated by Django 5.2.3 on 2025-08-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthentication', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('PASTOR', 'Pastor'), ('ASSISTANT_PASTOR', 'Assistant Pastor'), ('EVANGELIST', 'Evangelist'), ('CHURCH_SECRETARY', 'Church Secretary'), ('CHURCH_MEMBER', 'Church Member')], default='CHURCH_MEMBER', max_length=20),
        ),
    ]
